# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  admin_name: Super Admin
  admin_email: admin@example.com
  admin_password: password
  domain_name: example.com
  secret_key_base: 1e34b7dd3411d7a30771f951b743f138bdb8453cb2eda555352b07bbd65505efe3f79f1eaaa545f26a7de7af23917fa5d75db6330725f64733f695c95ab40894

test:
  domain_name: example.com 
  secret_key_base: dedad6af5126cb177ff2ec665dfb1fd1791785de4c037680c3226a0e1760ac6ef542a1a436dcf821ae78f042185a250b0576451b9976143a8c2e453c8f0e79e5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  admin_name: <%= ENV["ADMIN_NAME"] %>
  admin_email: <%= ENV["ADMIN_EMAIL"] %>
  admin_password: <%= ENV["ADMIN_PASSWORD"] %>
  domain_name: <%= ENV["DOMAIN_NAME"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
